config/routes.rb
Clf004::Application.routes.draw do
  resources :question_categories

  resources :answers

  resources :questions

  resources :aliases

  resources :simple_values

  resources :children

  resources :spouses

  resources :dependents

  resources :settlors do
    member do
      get 'basic'
      get 'spouse'
      get 'considerations'
      get 'assets'
      get 'liabilities'
      get 'insurance'
      get 'net_worth'
      get 'settlor_children'
      get 'spouse_children'
    end
  end

  resources :email_addresses

  resources :phone_numbers

  resources :mailing_addresses

  resources :residential_addresses

  resources :addresses

  resources :dependent_relationships

  resources :people

  get "welcome/index"
  get "welcome/wizard", as: :wizard_welcome
  get "welcome/wizard_bar", as: :wizard_bar_welcome

  devise_for :users

  root :to => 'welcome#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :address_01, :address_02, :city, :state, :zip, :type

  has_many :people, as: :person
end

app/models/alias.rb
class Alias < SimpleValue
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :person_id, :question_id, :value, :person, :question

  belongs_to :person
  belongs_to :question
end

app/models/child.rb
class Child < Dependent
end

app/models/dependent.rb
class Dependent < Person
end

app/models/email_address.rb
class EmailAddress < SimpleValue
end

app/models/mailing_address.rb
class MailingAddress < Address
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :alive, :born_at, :full_legal_name, :has_special_needs, :marital_status, :us_citizen, :type

  attr_accessible :us_citizen_yn
  attr_accessor :us_citizen_yn

  has_many :address_associations
  has_many :addresses, through: :address_associations

  has_one  :mailing_address_association
  has_one  :mailing_address, through: :mailing_address_association

  has_one  :residential_address_association
  has_one  :residential_address, through: :residential_address_association

  has_many :simple_value_associations
  has_many :simple_values, through: :simple_value_associations

  has_many :alias_associations
  has_many :aliases, through: :alias_associations

  has_many :phone_number_associations
  has_many :phone_numbers, through: :phone_number_associations

  has_many :email_address_associations
  has_many :email_addresses, through: :email_address_associations

  has_many :dependent_associations
  has_many :dependents, through: :dependent_associations

  has_one :spouse_association
  has_one :spouse, through: :spouse_association

  has_many :child_associations
  has_many :children, through: :child_associations

  def us_citizen_yn
    ((self.us_citizen?) ? "yes" : "no")
  end

  def us_citizen_yn=(value)
    self.us_citizen = ((value == "yes") ? true : false)
  end
end

app/models/phone_number.rb
class PhoneNumber < SimpleValue
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :category_id, :notes_required_for_response, :order_position, :phrase, :category

  belongs_to :category, class_name: "QuestionCategory"
end

app/models/settlor.rb
class Settlor < Person
  attr_accessible :joint_children_with_spouse, :estimated_net_worth
  attr_accessor :joint_children_with_spouse, :estimated_net_worth
end

app/models/simple_value.rb
class SimpleValue < ActiveRecord::Base
  attr_accessible :type, :value
end

app/models/spouse.rb
class Spouse < Dependent
end

app/models/user.rb
class User < ActiveRecord::Base
  # https://github.com/martinrehfeld/role_model
  include RoleModel

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # optionally set the integer attribute to store the roles in,
  # :roles_mask is the default
  roles_attribute :roles_mask

  # declare the valid roles -- do not change the order if you add more
  # roles later, always append them at the end!
  roles :admin, :manager, :associate
end

app/controllers/dependents_controller.rb
class DependentsController < ApplicationController
  # GET /dependents
  # GET /dependents.json
  def index
    @dependents = Dependent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dependents }
    end
  end

  # GET /dependents/1
  # GET /dependents/1.json
  def show
    @dependent = Dependent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dependent }
    end
  end

  # GET /dependents/new
  # GET /dependents/new.json
  def new
    @dependent = Dependent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dependent }
    end
  end

  # GET /dependents/1/edit
  def edit
    @dependent = Dependent.find(params[:id])
  end

  # POST /dependents
  # POST /dependents.json
  def create
    @dependent = Dependent.new(params[:dependent])

    respond_to do |format|
      if @dependent.save
        format.html { redirect_to @dependent, notice: 'Dependent was successfully created.' }
        format.json { render json: @dependent, status: :created, location: @dependent }
      else
        format.html { render action: "new" }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dependents/1
  # PUT /dependents/1.json
  def update
    @dependent = Dependent.find(params[:id])

    respond_to do |format|
      if @dependent.update_attributes(params[:dependent])
        format.html { redirect_to @dependent, notice: 'Dependent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependents/1
  # DELETE /dependents/1.json
  def destroy
    @dependent = Dependent.find(params[:id])
    @dependent.destroy

    respond_to do |format|
      format.html { redirect_to dependents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/aliases_helper.rb
module AliasesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/dependents_helper.rb
module DependentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/settlors_helper.rb
module SettlorsHelper
end

app/helpers/spouses_helper.rb
module SpousesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dependents/_form.html.erb
<%= form_for(@dependent) do |f| %>
  <% if @dependent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dependent.errors.count, "error") %> prohibited this dependent from being saved:</h2>

      <ul>
      <% @dependent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_legal_name %><br />
    <%= f.text_field :full_legal_name %>
  </div>
  <div class="field">
    <%= f.label :born_at %><br />
    <%= f.datetime_select :born_at %>
  </div>
  <div class="field">
    <%= f.label :us_citizen %><br />
    <%= f.check_box :us_citizen %>
  </div>
  <div class="field">
    <%= f.label :marital_status %><br />
    <%= f.text_field :marital_status %>
  </div>
  <div class="field">
    <%= f.label :alive %><br />
    <%= f.check_box :alive %>
  </div>
  <div class="field">
    <%= f.label :has_special_needs %><br />
    <%= f.check_box :has_special_needs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dependents/edit.html.erb
<h1>Editing dependent</h1>

<%= render 'form' %>

<%= link_to 'Show', @dependent %> |
<%= link_to 'Back', dependents_path %>

app/views/dependents/index.html.erb
<h1>Listing dependents</h1>

<table>
  <tr>
    <th>Full legal name</th>
    <th>Born at</th>
    <th>Us citizen</th>
    <th>Marital status</th>
    <th>Alive</th>
    <th>Has special needs</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dependents.each do |dependent| %>
  <tr>
    <td><%= dependent.full_legal_name %></td>
    <td><%= dependent.born_at %></td>
    <td><%= dependent.us_citizen %></td>
    <td><%= dependent.marital_status %></td>
    <td><%= dependent.alive %></td>
    <td><%= dependent.has_special_needs %></td>
    <td><%= link_to 'Show', dependent %></td>
    <td><%= link_to 'Edit', edit_dependent_path(dependent) %></td>
    <td><%= link_to 'Destroy', dependent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dependent', new_dependent_path %>

app/views/dependents/new.html.erb
<h1>New dependent</h1>

<%= render 'form' %>

<%= link_to 'Back', dependents_path %>

app/views/dependents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Full legal name:</b>
  <%= @dependent.full_legal_name %>
</p>

<p>
  <b>Born at:</b>
  <%= @dependent.born_at %>
</p>

<p>
  <b>Us citizen:</b>
  <%= @dependent.us_citizen %>
</p>

<p>
  <b>Marital status:</b>
  <%= @dependent.marital_status %>
</p>

<p>
  <b>Alive:</b>
  <%= @dependent.alive %>
</p>

<p>
  <b>Has special needs:</b>
  <%= @dependent.has_special_needs %>
</p>


<%= link_to 'Edit', edit_dependent_path(@dependent) %> |
<%= link_to 'Back', dependents_path %>