config/routes.rb
Clf004::Application.routes.draw do
  resources :question_categories

  resources :answers

  resources :questions

  resources :aliases

  resources :simple_values

  resources :children

  resources :spouses

  resources :dependents

  resources :settlors do
    member do
      get 'basic'
      get 'spouse'
      get 'considerations'
      get 'assets'
      get 'liabilities'
      get 'insurance'
      get 'net_worth'
      get 'settlor_children'
      get 'spouse_children'
    end
  end

  resources :email_addresses

  resources :phone_numbers

  resources :mailing_addresses

  resources :residential_addresses

  resources :addresses

  resources :dependent_relationships

  resources :people

  get "welcome/index"
  get "welcome/wizard", as: :wizard_welcome
  get "welcome/wizard_bar", as: :wizard_bar_welcome

  devise_for :users

  root :to => 'welcome#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :address_01, :address_02, :city, :state, :zip, :type

  has_many :people, as: :person
end

app/models/alias.rb
class Alias < SimpleValue
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :person_id, :question_id, :value, :person, :question

  belongs_to :person
  belongs_to :question
end

app/models/child.rb
class Child < Dependent
end

app/models/dependent.rb
class Dependent < Person
end

app/models/email_address.rb
class EmailAddress < SimpleValue
end

app/models/mailing_address.rb
class MailingAddress < Address
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :alive, :born_at, :full_legal_name, :has_special_needs, :marital_status, :us_citizen, :type

  attr_accessible :us_citizen_yn
  attr_accessor :us_citizen_yn

  has_many :address_associations
  has_many :addresses, through: :address_associations

  has_one  :mailing_address_association
  has_one  :mailing_address, through: :mailing_address_association

  has_one  :residential_address_association
  has_one  :residential_address, through: :residential_address_association

  has_many :simple_value_associations
  has_many :simple_values, through: :simple_value_associations

  has_many :alias_associations
  has_many :aliases, through: :alias_associations

  has_many :phone_number_associations
  has_many :phone_numbers, through: :phone_number_associations

  has_many :email_address_associations
  has_many :email_addresses, through: :email_address_associations

  has_many :dependent_associations
  has_many :dependents, through: :dependent_associations

  has_one :spouse_association
  has_one :spouse, through: :spouse_association

  has_many :child_associations
  has_many :children, through: :child_associations

  def us_citizen_yn
    ((self.us_citizen?) ? "yes" : "no")
  end

  def us_citizen_yn=(value)
    self.us_citizen = ((value == "yes") ? true : false)
  end
end

app/models/phone_number.rb
class PhoneNumber < SimpleValue
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :category_id, :notes_required_for_response, :order_position, :phrase, :category

  belongs_to :category, class_name: "QuestionCategory"
end

app/models/settlor.rb
class Settlor < Person
  attr_accessible :joint_children_with_spouse, :estimated_net_worth
  attr_accessor :joint_children_with_spouse, :estimated_net_worth
end

app/models/simple_value.rb
class SimpleValue < ActiveRecord::Base
  attr_accessible :type, :value
end

app/models/spouse.rb
class Spouse < Dependent
end

app/models/user.rb
class User < ActiveRecord::Base
  # https://github.com/martinrehfeld/role_model
  include RoleModel

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # optionally set the integer attribute to store the roles in,
  # :roles_mask is the default
  roles_attribute :roles_mask

  # declare the valid roles -- do not change the order if you add more
  # roles later, always append them at the end!
  roles :admin, :manager, :associate
end

app/controllers/residential_addresses_controller.rb
class ResidentialAddressesController < ApplicationController
  # GET /residential_addresses
  # GET /residential_addresses.json
  def index
    @residential_addresses = ResidentialAddress.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @residential_addresses }
    end
  end

  # GET /residential_addresses/1
  # GET /residential_addresses/1.json
  def show
    @residential_address = ResidentialAddress.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @residential_address }
    end
  end

  # GET /residential_addresses/new
  # GET /residential_addresses/new.json
  def new
    @residential_address = ResidentialAddress.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @residential_address }
    end
  end

  # GET /residential_addresses/1/edit
  def edit
    @residential_address = ResidentialAddress.find(params[:id])
  end

  # POST /residential_addresses
  # POST /residential_addresses.json
  def create
    @residential_address = ResidentialAddress.new(params[:residential_address])

    respond_to do |format|
      if @residential_address.save
        format.html { redirect_to @residential_address, notice: 'Residential address was successfully created.' }
        format.json { render json: @residential_address, status: :created, location: @residential_address }
      else
        format.html { render action: "new" }
        format.json { render json: @residential_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /residential_addresses/1
  # PUT /residential_addresses/1.json
  def update
    @residential_address = ResidentialAddress.find(params[:id])

    respond_to do |format|
      if @residential_address.update_attributes(params[:residential_address])
        format.html { redirect_to @residential_address, notice: 'Residential address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @residential_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residential_addresses/1
  # DELETE /residential_addresses/1.json
  def destroy
    @residential_address = ResidentialAddress.find(params[:id])
    @residential_address.destroy

    respond_to do |format|
      format.html { redirect_to residential_addresses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/aliases_helper.rb
module AliasesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/residential_addresses_helper.rb
module ResidentialAddressesHelper
end

app/helpers/spouses_helper.rb
module SpousesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/residential_addresses/_form.html.erb
<%= form_for(@residential_address) do |f| %>
  <% if @residential_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@residential_address.errors.count, "error") %> prohibited this residential_address from being saved:</h2>

      <ul>
      <% @residential_address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address_01 %><br />
    <%= f.text_field :address_01 %>
  </div>
  <div class="field">
    <%= f.label :address_02 %><br />
    <%= f.text_field :address_02 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/residential_addresses/edit.html.erb
<h1>Editing residential_address</h1>

<%= render 'form' %>

<%= link_to 'Show', @residential_address %> |
<%= link_to 'Back', residential_addresses_path %>

app/views/residential_addresses/index.html.erb
<h1>Listing residential_addresses</h1>

<table>
  <tr>
    <th>Address 01</th>
    <th>Address 02</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @residential_addresses.each do |residential_address| %>
  <tr>
    <td><%= residential_address.address_01 %></td>
    <td><%= residential_address.address_02 %></td>
    <td><%= residential_address.city %></td>
    <td><%= residential_address.state %></td>
    <td><%= residential_address.zip %></td>
    <td><%= link_to 'Show', residential_address %></td>
    <td><%= link_to 'Edit', edit_residential_address_path(residential_address) %></td>
    <td><%= link_to 'Destroy', residential_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Residential address', new_residential_address_path %>

app/views/residential_addresses/new.html.erb
<h1>New residential_address</h1>

<%= render 'form' %>

<%= link_to 'Back', residential_addresses_path %>

app/views/residential_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address 01:</b>
  <%= @residential_address.address_01 %>
</p>

<p>
  <b>Address 02:</b>
  <%= @residential_address.address_02 %>
</p>

<p>
  <b>City:</b>
  <%= @residential_address.city %>
</p>

<p>
  <b>State:</b>
  <%= @residential_address.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @residential_address.zip %>
</p>


<%= link_to 'Edit', edit_residential_address_path(@residential_address) %> |
<%= link_to 'Back', residential_addresses_path %>