config/routes.rb
Clf004::Application.routes.draw do
  resources :question_categories

  resources :answers

  resources :questions

  resources :aliases

  resources :simple_values

  resources :children

  resources :spouses

  resources :dependents

  resources :settlors do
    member do
      get 'basic'
      get 'spouse'
      get 'considerations'
      get 'assets'
      get 'liabilities'
      get 'insurance'
      get 'net_worth'
      get 'settlor_children'
      get 'spouse_children'
    end
  end

  resources :email_addresses

  resources :phone_numbers

  resources :mailing_addresses

  resources :residential_addresses

  resources :addresses

  resources :dependent_relationships

  resources :people

  get "welcome/index"
  get "welcome/wizard", as: :wizard_welcome
  get "welcome/wizard_bar", as: :wizard_bar_welcome

  devise_for :users

  root :to => 'welcome#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :address_01, :address_02, :city, :state, :zip, :type

  has_many :people, as: :person
end

app/models/alias.rb
class Alias < SimpleValue
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :person_id, :question_id, :value, :person, :question

  belongs_to :person
  belongs_to :question
end

app/models/child.rb
class Child < Dependent
end

app/models/dependent.rb
class Dependent < Person
end

app/models/email_address.rb
class EmailAddress < SimpleValue
end

app/models/mailing_address.rb
class MailingAddress < Address
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :alive, :born_at, :full_legal_name, :has_special_needs, :marital_status, :us_citizen, :type

  attr_accessible :us_citizen_yn
  attr_accessor :us_citizen_yn

  has_many :address_associations
  has_many :addresses, through: :address_associations

  has_one  :mailing_address_association
  has_one  :mailing_address, through: :mailing_address_association

  has_one  :residential_address_association
  has_one  :residential_address, through: :residential_address_association

  has_many :simple_value_associations
  has_many :simple_values, through: :simple_value_associations

  has_many :alias_associations
  has_many :aliases, through: :alias_associations

  has_many :phone_number_associations
  has_many :phone_numbers, through: :phone_number_associations

  has_many :email_address_associations
  has_many :email_addresses, through: :email_address_associations

  has_many :dependent_associations
  has_many :dependents, through: :dependent_associations

  has_one :spouse_association
  has_one :spouse, through: :spouse_association

  has_many :child_associations
  has_many :children, through: :child_associations

  def us_citizen_yn
    ((self.us_citizen?) ? "yes" : "no")
  end

  def us_citizen_yn=(value)
    self.us_citizen = ((value == "yes") ? true : false)
  end
end

app/models/phone_number.rb
class PhoneNumber < SimpleValue
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :category_id, :notes_required_for_response, :order_position, :phrase, :category

  belongs_to :category, class_name: "QuestionCategory"
end

app/models/settlor.rb
class Settlor < Person
  attr_accessible :joint_children_with_spouse, :estimated_net_worth
  attr_accessor :joint_children_with_spouse, :estimated_net_worth
end

app/models/simple_value.rb
class SimpleValue < ActiveRecord::Base
  attr_accessible :type, :value
end

app/models/spouse.rb
class Spouse < Dependent
end

app/models/user.rb
class User < ActiveRecord::Base
  # https://github.com/martinrehfeld/role_model
  include RoleModel

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # optionally set the integer attribute to store the roles in,
  # :roles_mask is the default
  roles_attribute :roles_mask

  # declare the valid roles -- do not change the order if you add more
  # roles later, always append them at the end!
  roles :admin, :manager, :associate
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/aliases_helper.rb
module AliasesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/settlors_helper.rb
module SettlorsHelper
end

app/helpers/spouses_helper.rb
module SpousesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br />
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.number_field :person_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>Value</th>
    <th>Question</th>
    <th>Person</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.value %></td>
    <td><%= answer.question_id %></td>
    <td><%= answer.person_id %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @answer.value %>
</p>

<p>
  <b>Question:</b>
  <%= @answer.question_id %>
</p>

<p>
  <b>Person:</b>
  <%= @answer.person_id %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>