config/routes.rb
Clf004::Application.routes.draw do
  resources :question_categories

  resources :answers

  resources :questions

  resources :aliases

  resources :simple_values

  resources :children

  resources :spouses

  resources :dependents

  resources :settlors do
    member do
      get 'basic'
      get 'spouse'
      get 'considerations'
      get 'assets'
      get 'liabilities'
      get 'insurance'
      get 'net_worth'
      get 'settlor_children'
      get 'spouse_children'
    end
  end

  resources :email_addresses

  resources :phone_numbers

  resources :mailing_addresses

  resources :residential_addresses

  resources :addresses

  resources :dependent_relationships

  resources :people

  get "welcome/index"
  get "welcome/wizard", as: :wizard_welcome
  get "welcome/wizard_bar", as: :wizard_bar_welcome

  devise_for :users

  root :to => 'welcome#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :address_01, :address_02, :city, :state, :zip, :type

  has_many :people, as: :person
end

app/models/alias.rb
class Alias < SimpleValue
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :person_id, :question_id, :value, :person, :question

  belongs_to :person
  belongs_to :question
end

app/models/child.rb
class Child < Dependent
end

app/models/dependent.rb
class Dependent < Person
end

app/models/email_address.rb
class EmailAddress < SimpleValue
end

app/models/mailing_address.rb
class MailingAddress < Address
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :alive, :born_at, :full_legal_name, :has_special_needs, :marital_status, :us_citizen, :type

  attr_accessible :us_citizen_yn
  attr_accessor :us_citizen_yn

  has_many :address_associations
  has_many :addresses, through: :address_associations

  has_one  :mailing_address_association
  has_one  :mailing_address, through: :mailing_address_association

  has_one  :residential_address_association
  has_one  :residential_address, through: :residential_address_association

  has_many :simple_value_associations
  has_many :simple_values, through: :simple_value_associations

  has_many :alias_associations
  has_many :aliases, through: :alias_associations

  has_many :phone_number_associations
  has_many :phone_numbers, through: :phone_number_associations

  has_many :email_address_associations
  has_many :email_addresses, through: :email_address_associations

  has_many :dependent_associations
  has_many :dependents, through: :dependent_associations

  has_one :spouse_association
  has_one :spouse, through: :spouse_association

  has_many :child_associations
  has_many :children, through: :child_associations

  def us_citizen_yn
    ((self.us_citizen?) ? "yes" : "no")
  end

  def us_citizen_yn=(value)
    self.us_citizen = ((value == "yes") ? true : false)
  end
end

app/models/phone_number.rb
class PhoneNumber < SimpleValue
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :category_id, :notes_required_for_response, :order_position, :phrase, :category

  belongs_to :category, class_name: "QuestionCategory"
end

app/models/settlor.rb
class Settlor < Person
  attr_accessible :joint_children_with_spouse, :estimated_net_worth
  attr_accessor :joint_children_with_spouse, :estimated_net_worth
end

app/models/simple_value.rb
class SimpleValue < ActiveRecord::Base
  attr_accessible :type, :value
end

app/models/spouse.rb
class Spouse < Dependent
end

app/models/user.rb
class User < ActiveRecord::Base
  # https://github.com/martinrehfeld/role_model
  include RoleModel

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # optionally set the integer attribute to store the roles in,
  # :roles_mask is the default
  roles_attribute :roles_mask

  # declare the valid roles -- do not change the order if you add more
  # roles later, always append them at the end!
  roles :admin, :manager, :associate
end

app/controllers/simple_values_controller.rb
class SimpleValuesController < ApplicationController
  # GET /simple_values
  # GET /simple_values.json
  def index
    @simple_values = SimpleValue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @simple_values }
    end
  end

  # GET /simple_values/1
  # GET /simple_values/1.json
  def show
    @simple_value = SimpleValue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @simple_value }
    end
  end

  # GET /simple_values/new
  # GET /simple_values/new.json
  def new
    @simple_value = SimpleValue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @simple_value }
    end
  end

  # GET /simple_values/1/edit
  def edit
    @simple_value = SimpleValue.find(params[:id])
  end

  # POST /simple_values
  # POST /simple_values.json
  def create
    @simple_value = SimpleValue.new(params[:simple_value])

    respond_to do |format|
      if @simple_value.save
        format.html { redirect_to @simple_value, notice: 'Simple value was successfully created.' }
        format.json { render json: @simple_value, status: :created, location: @simple_value }
      else
        format.html { render action: "new" }
        format.json { render json: @simple_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /simple_values/1
  # PUT /simple_values/1.json
  def update
    @simple_value = SimpleValue.find(params[:id])

    respond_to do |format|
      if @simple_value.update_attributes(params[:simple_value])
        format.html { redirect_to @simple_value, notice: 'Simple value was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @simple_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simple_values/1
  # DELETE /simple_values/1.json
  def destroy
    @simple_value = SimpleValue.find(params[:id])
    @simple_value.destroy

    respond_to do |format|
      format.html { redirect_to simple_values_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/aliases_helper.rb
module AliasesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/settlors_helper.rb
module SettlorsHelper
end

app/helpers/simple_values_helper.rb
module SimpleValuesHelper
end

app/helpers/spouses_helper.rb
module SpousesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/simple_values/_form.html.erb
<%= form_for(@simple_value) do |f| %>
  <% if @simple_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@simple_value.errors.count, "error") %> prohibited this simple_value from being saved:</h2>

      <ul>
      <% @simple_value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/simple_values/edit.html.erb
<h1>Editing simple_value</h1>

<%= render 'form' %>

<%= link_to 'Show', @simple_value %> |
<%= link_to 'Back', simple_values_path %>

app/views/simple_values/index.html.erb
<h1>Listing simple_values</h1>

<table>
  <tr>
    <th>Value</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @simple_values.each do |simple_value| %>
  <tr>
    <td><%= simple_value.value %></td>
    <td><%= simple_value.type %></td>
    <td><%= link_to 'Show', simple_value %></td>
    <td><%= link_to 'Edit', edit_simple_value_path(simple_value) %></td>
    <td><%= link_to 'Destroy', simple_value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Simple value', new_simple_value_path %>

app/views/simple_values/new.html.erb
<h1>New simple_value</h1>

<%= render 'form' %>

<%= link_to 'Back', simple_values_path %>

app/views/simple_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @simple_value.value %>
</p>

<p>
  <b>Type:</b>
  <%= @simple_value.type %>
</p>


<%= link_to 'Edit', edit_simple_value_path(@simple_value) %> |
<%= link_to 'Back', simple_values_path %>